name: 📄 Add New Paper
description: Add a new paper to the collection
title: "[ADD] "
labels: ["enhancement", "data"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        새로운 논문을 추가해주세요. 아래 양식을 작성해주시면 자동으로 README.md에 추가됩니다.

  - type: input
    id: paper_type
    attributes:
      label: 논문 유형
      description: 논문의 유형을 선택해주세요 (예: 📜 Paper, 🧑🏻‍💻 Code, 🗞️ News)
      placeholder: "📜 Paper"
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: 기관/저자
      description: 논문의 주요 기관이나 저자명을 입력해주세요
      placeholder: "OpenAI"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: 논문 제목
      description: 논문의 제목을 입력해주세요
      placeholder: "GPT-4: A Large Language Model"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 논문 링크
      description: 논문의 URL을 입력해주세요
      placeholder: "https://arxiv.org/abs/2303.08774"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 논문 설명 (선택사항)
      description: 논문에 대한 간단한 설명을 입력해주세요
      placeholder: "GPT-4는 대규모 언어 모델로..."
    validations:
      required: false

  - type: input
    id: conference
    attributes:
      label: 학회/저널 (선택사항)
      description: 발표된 학회나 저널명을 입력해주세요
      placeholder: "NeurIPS 2023"
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보 (선택사항)
      description: 기타 추가하고 싶은 정보가 있다면 입력해주세요
      placeholder: "특별한 점이나 주목할 만한 내용..."
    validations:
      required: false
