name: 일괄 항목 추가
description: 여러 항목을 한 번에 추가합니다
title: "[README 업데이트] 일괄 추가"
labels: ["enhancement", "data"]
assignees: ["chanmuzi"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 일괄 항목 추가

        여러 항목을 한 번에 추가할 수 있습니다. 아래 정보를 입력하고 마크다운 형식으로 항목들을 작성해주세요.

  - type: dropdown
    id: year
    attributes:
      label: 연도 (Year) *
      description: 연도를 선택하세요
      options:
        - "2025"
        - "2024"
        - "2023"
    validations:
      required: true

  - type: dropdown
    id: month
    attributes:
      label: 월 (Month) *
      description: 월을 선택하세요
      options:
        - "January"
        - "February"
        - "March"
        - "April"
        - "May"
        - "June"
        - "July"
        - "August"
        - "September"
        - "October"
        - "November"
        - "December"
    validations:
      required: true

  - type: dropdown
    id: week
    attributes:
      label: 주차 (Week) *
      description: 주차를 선택하세요
      options:
        - "1st week"
        - "2nd week"
        - "3rd week"
        - "4th week"
        - "5th week"
    validations:
      required: true

  - type: textarea
    id: markdown_items
    attributes:
      label: 마크다운 형식 항목들 (Markdown Items) *
      description: 아래 형식에 맞춰 항목들을 작성하세요. ** 기호는 자동으로 제거됩니다.
      placeholder: |
        - 📜 [UC Berkeley] [**MCP-Bench: Benchmarking Tool-Using LLM Agents with Complex Real-World Tasks via MCP Servers**](https://arxiv.org/abs/2508.20453)
          - LLM의 tool use, cross-tool coordination, precise parameter control 등을 요하는 realistic, multi-step tasks 평가 벤치마크
          - MCP 기반으로 build 되어 LLM을 28개의 대표적인 live MCP servers와 연결하여 다양한 도메인(finance, traveling 등)을 다룸
          - multi-faceted evaluation framework 제안

        - 🧑🏻‍💻 [xAI] [**Grok Code Fast 1**](https://x.ai/news/grok-code-fast-1)
          - grep, terminal, file editing 등 common tools 사용을 master
          - GitHub Copilot, Cline, Cursor, Roo Code, Windsurf 등에서 사용 가능
          - TS, Python, Java, Rust, C++, Go 등 다양한 언어를 다룰 수 있으며, 서빙단에서 속도를 최적화했음을 언급
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보 (Additional Info)
      description: 기타 참고사항이 있다면 작성하세요
      placeholder: "추가 정보나 특이사항을 입력하세요"
      render: markdown

  - type: markdown
    attributes:
      value: |
        ---

        **참고**: 이 Issue가 승인되면 자동으로 README.md에 추가되고 웹사이트가 업데이트됩니다.
