name: Auto Parse README and Update Website

on:
  push:
    paths: ["README.md"]
  workflow_dispatch: # 수동 실행 가능

jobs:
  parse-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Parse README.md
        run: |
          python scripts/parse_readme.py

              - name: Commit and push changes
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data/items.json
            git status
            git diff --staged || echo "No changes to commit"
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Auto-update items.json from README.md"
              git push
            fi
