name: Parse README and Update JSON

on:
  push:
    branches: [main]
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  parse-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.head_commit.author.name != 'GitHub Action'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Parse README and update JSON
        run: |
          python3 scripts/parse_readme.py

      - name: Sync to docs folder
        run: |
          cp data/items.json docs/data/items.json

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/items.json docs/data/items.json
          git commit -m "Auto-parse: Update items.json from README.md [skip ci]"
          git push origin main
