name: Sync README to JSON
on:
  push:
    paths: ["README.md"]
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install regex

      - name: Parse README to JSON
        run: python scripts/parse_readme.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet data/items.json; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.no_changes == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/items.json
          git commit -m "chore: sync items.json from README [skip ci]"
          git pull --rebase origin main
          git push

      - name: No changes
        if: steps.check_changes.outputs.no_changes == 'true'
        run: echo "No changes detected in items.json"
